services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kapital-api:latest
    container_name: kapital-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    networks:
      - kapital-network

  redis:
    image: redis:7-alpine
    container_name: kapital-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - kapital-network

networks:
  kapital-network:
    driver: bridge

volumes:
  redis-data: