### Request ###

GET /v1/ticker/AAPL/earnings HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 16384 
content-type: application/json 
date: Sat,05 Apr 2025 22:35:49 GMT 
server: uvicorn 

[
  {
    "index": 0,
    "Shares": 108136,
    "Value": 24184658,
    "URL": "",
    "Text": "Sale at price 221.77 - 224.76 per share.",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2025-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 1,
    "Shares": 38822,
    "Value": 8683252,
    "URL": "",
    "Text": "Sale at price 221.68 - 224.62 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2025-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 2,
    "Shares": 35493,
    "Value": 7950691,
    "URL": "",
    "Text": "Sale at price 223.48 - 225.03 per share.",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2025-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 3,
    "Shares": 218568,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2025-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 4,
    "Shares": 74535,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2025-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 5,
    "Shares": 74535,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2025-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 6,
    "Shares": 1516,
    "Value": 343147,
    "URL": "",
    "Text": "Sale at price 226.35 per share.",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-02-03 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 7,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "AUSTIN WANDA M",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 8,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "LOZANO MONICA C.",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 9,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "GORSKY ALEX",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 10,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "SUGAR RONALD D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 11,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WAGNER SUSAN L",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 12,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 13,
    "Shares": 1516,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "JUNG ANDREA",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2025-01-31 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 14,
    "Shares": 100000,
    "Value": 24997395,
    "URL": "",
    "Text": "Sale at price 248.61 - 251.10 per share.",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2024-12-16 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 15,
    "Shares": 200000,
    "Value": 45464500,
    "URL": "",
    "Text": "Sale at price 224.68 - 229.28 per share.",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-11-19 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 16,
    "Shares": 4130,
    "Value": 945233,
    "URL": "",
    "Text": "Sale at price 228.87 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-11-18 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 17,
    "Shares": 8000,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-11-05 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 18,
    "Shares": 8115,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-10-15 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 19,
    "Shares": 59305,
    "Value": 13433769,
    "URL": "",
    "Text": "Sale at price 226.52 per share.",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2024-10-04 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 20,
    "Shares": 61019,
    "Value": 13843382,
    "URL": "",
    "Text": "Sale at price 226.72 - 227.13 per share.",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-10-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 21,
    "Shares": 223986,
    "Value": 50276355,
    "URL": "",
    "Text": "Sale at price 223.75 - 226.57 per share.",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2024-10-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 22,
    "Shares": 61019,
    "Value": 13802297,
    "URL": "",
    "Text": "Sale at price 223.79 - 227.24 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-10-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 23,
    "Shares": 59730,
    "Value": 13550148,
    "URL": "",
    "Text": "Sale at price 226.80 - 227.22 per share.",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2024-10-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 24,
    "Shares": 127282,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-10-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 25,
    "Shares": 127282,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2024-10-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 26,
    "Shares": 477301,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2024-10-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 27,
    "Shares": 127282,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-10-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 28,
    "Shares": 127282,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2024-10-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 29,
    "Shares": 8706,
    "Value": 1958850,
    "URL": "",
    "Text": "Sale at price 225.00 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-08-15 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 30,
    "Shares": 5178,
    "Value": 1121037,
    "URL": "",
    "Text": "Sale at price 216.50 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-08-09 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 31,
    "Shares": 4500,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-08-07 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 32,
    "Shares": 100000,
    "Value": 20643512,
    "URL": "",
    "Text": "Sale at price 206.42 - 207.05 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-08-05 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 33,
    "Shares": 75000,
    "Value": 14368500,
    "URL": "",
    "Text": "Sale at price 191.58 per share.",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-05-30 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 34,
    "Shares": 4999,
    "Value": 951785,
    "URL": "",
    "Text": "Sale at price 190.40 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-05-15 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 35,
    "Shares": 1850,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-05-10 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 36,
    "Shares": 8119,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-04-15 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 37,
    "Shares": 53194,
    "Value": 9261933,
    "URL": "",
    "Text": "Sale at price 173.19 - 175.02 per share.",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2024-04-11 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 38,
    "Shares": 59162,
    "Value": 10188880,
    "URL": "",
    "Text": "Sale at price 172.22 per share.",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2024-04-11 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 39,
    "Shares": 54732,
    "Value": 9244782,
    "URL": "",
    "Text": "Sale at price 168.91 per share.",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 40,
    "Shares": 196410,
    "Value": 33258614,
    "URL": "",
    "Text": "Sale at price 168.62 - 170.03 per share.",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2024-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 41,
    "Shares": 54732,
    "Value": 9244235,
    "URL": "",
    "Text": "Sale at price 168.90 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-04-02 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 42,
    "Shares": 113309,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2024-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 43,
    "Shares": 113309,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2024-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 44,
    "Shares": 196410,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2024-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 45,
    "Shares": 113309,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2024-04-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 46,
    "Shares": 113309,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2024-04-01 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 47,
    "Shares": 100000,
    "Value": 18094000,
    "URL": "",
    "Text": "Sale at price 180.94 per share.",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 48,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "BELL JAMES A",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 49,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "LOZANO MONICA C.",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 50,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "GORSKY ALEX",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 51,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "GORE ALBERT A JR",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 52,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "SUGAR RONALD D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 53,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WAGNER SUSAN L",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 54,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "LEVINSON ARTHUR D",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 55,
    "Shares": 1852,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "JUNG ANDREA",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2024-02-01 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 56,
    "Shares": 5513,
    "Value": 1058496,
    "URL": "",
    "Text": "Sale at price 192.00 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-11-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 57,
    "Shares": 123448,
    "Value": 23305748,
    "URL": "",
    "Text": "Sale at price 188.79 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-11-17 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 58,
    "Shares": 123448,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-11-16 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 59,
    "Shares": 4806,
    "Value": 884496,
    "URL": "",
    "Text": "Sale at price 184.04 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-11-10 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 60,
    "Shares": 10785,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-10-13 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 61,
    "Shares": 63695,
    "Value": 11356182,
    "URL": "",
    "Text": "Sale at price 177.89 - 178.91 per share.",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2023-10-09 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 62,
    "Shares": 69785,
    "Value": 12351945,
    "URL": "",
    "Text": "Sale at price 177.00 per share.",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2023-10-06 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 63,
    "Shares": 65536,
    "Value": 11279673,
    "URL": "",
    "Text": "Sale at price 172.08 - 172.65 per share.",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-10-03 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 64,
    "Shares": 240569,
    "Value": 41498284,
    "URL": "",
    "Text": "Sale at price 171.42 - 173.18 per share.",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2023-10-03 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 65,
    "Shares": 65536,
    "Value": 11278365,
    "URL": "",
    "Text": "Sale at price 171.62 - 173.24 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-10-03 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 66,
    "Shares": 136268,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-09-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 67,
    "Shares": 136268,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2023-09-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 68,
    "Shares": 511000,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "COOK TIMOTHY D",
    "Position": "Chief Executive Officer",
    "Transaction": "",
    "Start Date": "2023-09-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 69,
    "Shares": 136268,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-09-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 70,
    "Shares": 136268,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "WILLIAMS JEFFREY E",
    "Position": "Chief Operating Officer",
    "Transaction": "",
    "Start Date": "2023-09-29 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 71,
    "Shares": 5600,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-08-08 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 72,
    "Shares": 15419,
    "Value": 2753217,
    "URL": "",
    "Text": "Sale at price 178.56 per share.",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-08-07 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 73,
    "Shares": 31896,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "O'BRIEN DEIRDRE",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-08-04 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 74,
    "Shares": 68642,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "JUNG ANDREA",
    "Position": "Director",
    "Transaction": "",
    "Start Date": "2023-05-16 00:00:00",
    "Ownership": "I"
  },
  {
    "index": 75,
    "Shares": 2900,
    "Value": 0,
    "URL": "",
    "Text": "Stock Gift at price 0.00 per share.",
    "Insider": "ADAMS KATHERINE L",
    "Position": "General Counsel",
    "Transaction": "",
    "Start Date": "2023-05-10 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 76,
    "Shares": 4092,
    "Value": 708980,
    "URL": "",
    "Text": "Sale at price 173.26 per share.",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-05-08 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 77,
    "Shares": 10792,
    "Value": null,
    "URL": "",
    "Text": "",
    "Insider": "KONDO CHRISTOPHER",
    "Position": "Officer",
    "Transaction": "",
    "Start Date": "2023-04-14 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 78,
    "Shares": 69996,
    "Value": 11566839,
    "URL": "",
    "Text": "Sale at price 165.25 per share.",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2023-04-13 00:00:00",
    "Ownership": "D"
  },
  {
    "index": 79,
    "Shares": 200,
    "Value": 32984,
    "URL": "",
    "Text": "Sale at price 164.92 per share.",
    "Insider": "MAESTRI LUCA",
    "Position": "Chief Financial Officer",
    "Transaction": "",
    "Start Date": "2023-04-06 00:00:00",
    "Ownership": "D"
  }
]