### Request ###

GET /v1/ticker/AAPL/isin HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 14 
content-type: application/json 
date: Sat,05 Apr 2025 22:38:08 GMT 
server: uvicorn 

"US0378331005"