### Request ###

GET /v1/ticker/AAPL/major-holders HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 202 
content-type: application/json 
date: Sat,05 Apr 2025 22:39:10 GMT 
server: uvicorn 

[
  {
    "index": "insidersPercentHeld",
    "Value": 0.0207
  },
  {
    "index": "institutionsPercentHeld",
    "Value": 0.62813
  },
  {
    "index": "institutionsFloatPercentHeld",
    "Value": 0.64141
  },
  {
    "index": "institutionsCount",
    "Value": 6950
  }
]