### Request ###

GET /v1/download?symbols=AAPL%2CKO&period=1mo&interval=1d&start=2025-01-01&end=2025-04-05&group_by=ticker&auto_adjust=true&back_adjust=false&actions=true&prepost=true&threads=true&repair=true&rounding=false HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 35709 
content-type: application/json 
date: Sat,05 Apr 2025 23:01:30 GMT 
server: uvicorn 

[
  {
    "('Date', '')": "2025-01-02 00:00:00",
    "('AAPL', 'Open')": 248.65660659999048,
    "('AAPL', 'High')": 248.826433311358,
    "('AAPL', 'Low')": 241.55442975303322,
    "('AAPL', 'Close')": 243.5821990966797,
    "('AAPL', 'Volume')": 55740700,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.893255754983585,
    "('KO', 'High')": 62.290327083764495,
    "('KO', 'Low')": 61.16860379869834,
    "('KO', 'Close')": 61.386993408203125,
    "('KO', 'Volume')": 12991000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-03 00:00:00",
    "('AAPL', 'Open')": 243.0927276611328,
    "('AAPL', 'High')": 243.91181916074598,
    "('AAPL', 'Low')": 241.624340886356,
    "('AAPL', 'Close')": 243.0927276611328,
    "('AAPL', 'Volume')": 40244100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.44655589480141,
    "('KO', 'High')": 61.62523761597134,
    "('KO', 'Low')": 61.168604447007716,
    "('KO', 'Close')": 61.29765319824219,
    "('KO', 'Volume')": 10403200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-06 00:00:00",
    "('AAPL', 'Open')": 244.04168187374515,
    "('AAPL', 'High')": 247.05836939894766,
    "('AAPL', 'Low')": 242.93290033169586,
    "('AAPL', 'Close')": 244.73092651367188,
    "('AAPL', 'Volume')": 45045600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.04948416900671,
    "('KO', 'High')": 61.11897108381982,
    "('KO', 'Low')": 60.215637404496505,
    "('KO', 'Close')": 60.364540100097656,
    "('KO', 'Volume')": 17924200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-07 00:00:00",
    "('AAPL', 'Open')": 242.71314361950866,
    "('AAPL', 'High')": 245.28032844029428,
    "('AAPL', 'Low')": 241.08494412707995,
    "('AAPL', 'Close')": 241.94400024414062,
    "('AAPL', 'Volume')": 40856000,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 60.662340200337496,
    "('KO', 'High')": 61.26787226019631,
    "('KO', 'Low')": 60.17592802195414,
    "('KO', 'Close')": 60.394317626953125,
    "('KO', 'Volume')": 17799600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-08 00:00:00",
    "('AAPL', 'Open')": 241.65429905026372,
    "('AAPL', 'High')": 243.44234164075266,
    "('AAPL', 'Low')": 239.78635773622742,
    "('AAPL', 'Close')": 242.43344116210938,
    "('AAPL', 'Volume')": 37628900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 60.543222908230796,
    "('KO', 'High')": 61.317507851065805,
    "('KO', 'Low')": 60.48366107156929,
    "('KO', 'Close')": 61.2579460144043,
    "('KO', 'Volume')": 14412400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-10 00:00:00",
    "('AAPL', 'Open')": 239.7463920626497,
    "('AAPL', 'High')": 239.8962364632009,
    "('AAPL', 'Low')": 232.74409661721964,
    "('AAPL', 'Close')": 236.58987426757812,
    "('AAPL', 'Volume')": 61710900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.12890103230223,
    "('KO', 'High')": 61.19838794834586,
    "('KO', 'Low')": 60.285125386875,
    "('KO', 'Close')": 60.62263488769531,
    "('KO', 'Volume')": 22425000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-13 00:00:00",
    "('AAPL', 'Open')": 233.27352322575203,
    "('AAPL', 'High')": 234.41227060505477,
    "('AAPL', 'Low')": 229.46771001708314,
    "('AAPL', 'Close')": 234.14256286621094,
    "('AAPL', 'Volume')": 49630700,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 60.68219592875893,
    "('KO', 'High')": 61.39691902537334,
    "('KO', 'Low')": 60.26527065121039,
    "('KO', 'Close')": 61.198387145996094,
    "('KO', 'Volume')": 18016200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-14 00:00:00",
    "('AAPL', 'Open')": 234.49217517741417,
    "('AAPL', 'High')": 235.8606656353981,
    "('AAPL', 'Low')": 232.21468051006943,
    "('AAPL', 'Close')": 233.02378845214844,
    "('AAPL', 'Volume')": 39435300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.20831194216533,
    "('KO', 'High')": 61.61530835181086,
    "('KO', 'Low')": 60.85094850213456,
    "('KO', 'Close')": 61.58552932739258,
    "('KO', 'Volume')": 16658300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-15 00:00:00",
    "('AAPL', 'Open')": 234.38230107288462,
    "('AAPL', 'High')": 238.6975638581554,
    "('AAPL', 'Low')": 234.17252500331003,
    "('AAPL', 'Close')": 237.60874938964844,
    "('AAPL', 'Volume')": 39832000,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.87340397115123,
    "('KO', 'High')": 62.16127670086423,
    "('KO', 'Low')": 61.2281640255215,
    "('KO', 'Close')": 61.3175048828125,
    "('KO', 'Volume')": 16187200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-16 00:00:00",
    "('AAPL', 'Open')": 237.089336348529,
    "('AAPL', 'High')": 237.74859991927732,
    "('AAPL', 'Low')": 227.7795647267042,
    "('AAPL', 'Close')": 228.00930786132812,
    "('AAPL', 'Volume')": 71759100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 60.9700693900409,
    "('KO', 'High')": 61.84362405929883,
    "('KO', 'Low')": 60.870803449177615,
    "('KO', 'Close')": 61.79399108886719,
    "('KO', 'Volume')": 12585500,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-17 00:00:00",
    "('AAPL', 'Open')": 231.86506609768284,
    "('AAPL', 'High')": 232.03487756376998,
    "('AAPL', 'Low')": 228.22906438809179,
    "('AAPL', 'Close')": 229.7274169921875,
    "('AAPL', 'Volume')": 68488300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.85355044666343,
    "('KO', 'High')": 62.31017981513981,
    "('KO', 'Low')": 61.71457283357027,
    "('KO', 'Close')": 62.25061798095703,
    "('KO', 'Volume')": 17948900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-21 00:00:00",
    "('AAPL', 'Open')": 223.75398423747347,
    "('AAPL', 'High')": 224.17352112887505,
    "('AAPL', 'Low')": 219.13906319002535,
    "('AAPL', 'Close')": 222.39547729492188,
    "('AAPL', 'Volume')": 98070400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.43922895475683,
    "('KO', 'High')": 62.766809577938204,
    "('KO', 'Low')": 61.843621969445486,
    "('KO', 'Close')": 61.96274185180664,
    "('KO', 'Volume')": 19817100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-22 00:00:00",
    "('AAPL', 'Open')": 219.54859611049605,
    "('AAPL', 'High')": 223.87384226456615,
    "('AAPL', 'Low')": 219.54859611049605,
    "('AAPL', 'Close')": 223.58416748046875,
    "('AAPL', 'Volume')": 64126500,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.66494021387,
    "('KO', 'High')": 61.83369685163256,
    "('KO', 'Low')": 61.20831084281117,
    "('KO', 'Close')": 61.327430725097656,
    "('KO', 'Volume')": 18191900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-23 00:00:00",
    "('AAPL', 'Open')": 224.493183388126,
    "('AAPL', 'High')": 226.78066167492807,
    "('AAPL', 'Low')": 222.05586069453574,
    "('AAPL', 'Close')": 223.41436767578125,
    "('AAPL', 'Volume')": 60234800,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.34728435361232,
    "('KO', 'High')": 61.52596606949709,
    "('KO', 'Low')": 60.92043400863789,
    "('KO', 'Close')": 61.079261779785156,
    "('KO', 'Volume')": 16528400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-24 00:00:00",
    "('AAPL', 'Open')": 224.53312753788666,
    "('AAPL', 'High')": 225.38220009721186,
    "('AAPL', 'Low')": 221.16683361690275,
    "('AAPL', 'Close')": 222.5353240966797,
    "('AAPL', 'Volume')": 54697900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 61.267872088197464,
    "('KO', 'High')": 61.55574481872562,
    "('KO', 'Low')": 60.989920649864665,
    "('KO', 'Close')": 61.46640396118164,
    "('KO', 'Volume')": 19244600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-27 00:00:00",
    "('AAPL', 'Open')": 223.77396171163917,
    "('AAPL', 'High')": 231.89502211760887,
    "('AAPL', 'Low')": 223.73399710835045,
    "('AAPL', 'Close')": 229.6075439453125,
    "('AAPL', 'Volume')": 94863400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.40944794678594,
    "('KO', 'High')": 63.70985297152916,
    "('KO', 'Low')": 62.01238039852861,
    "('KO', 'Close')": 63.402122497558594,
    "('KO', 'Volume')": 20742900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-28 00:00:00",
    "('AAPL', 'Open')": 230.59647127201654,
    "('AAPL', 'High')": 239.9262098046868,
    "('AAPL', 'Low')": 230.55650666713984,
    "('AAPL', 'Close')": 237.99832153320312,
    "('AAPL', 'Volume')": 75707600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.04475639662816,
    "('KO', 'High')": 63.57087646135838,
    "('KO', 'Low')": 61.8237672050419,
    "('KO', 'Close')": 61.90318298339844,
    "('KO', 'Volume')": 14956000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-29 00:00:00",
    "('AAPL', 'Open')": 233.86287156365174,
    "('AAPL', 'High')": 239.5965730646729,
    "('AAPL', 'Low')": 233.75299176206667,
    "('AAPL', 'Close')": 239.0971221923828,
    "('AAPL', 'Volume')": 45486100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.1017207661784,
    "('KO', 'High')": 62.895859643136625,
    "('KO', 'Low')": 62.09179190016794,
    "('KO', 'Close')": 62.36974334716797,
    "('KO', 'Volume')": 11325600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-30 00:00:00",
    "('AAPL', 'Open')": 238.40787147181928,
    "('AAPL', 'High')": 240.52553823889048,
    "('AAPL', 'Low')": 236.94948349745044,
    "('AAPL', 'Close')": 237.3290557861328,
    "('AAPL', 'Volume')": 55658300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.38226728189863,
    "('KO', 'High')": 63.81904649900702,
    "('KO', 'Low')": 62.76681013304467,
    "('KO', 'Close')": 63.580806732177734,
    "('KO', 'Volume')": 13201000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-01-31 00:00:00",
    "('AAPL', 'Open')": 246.91852728753366,
    "('AAPL', 'High')": 246.91852728753366,
    "('AAPL', 'Low')": 233.18362815459494,
    "('AAPL', 'Close')": 235.74081420898438,
    "('AAPL', 'Volume')": 101075100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.23336993008949,
    "('KO', 'High')": 63.461684623398604,
    "('KO', 'Low')": 62.92563945471481,
    "('KO', 'Close')": 63.01498031616211,
    "('KO', 'Volume')": 12102100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-03 00:00:00",
    "('AAPL', 'Open')": 229.73741895869952,
    "('AAPL', 'High')": 231.5753945205246,
    "('AAPL', 'Low')": 225.45212191586603,
    "('AAPL', 'Close')": 227.75958251953125,
    "('AAPL', 'Volume')": 73063300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.71717625749673,
    "('KO', 'High')": 63.16388054728714,
    "('KO', 'Low')": 61.972670370096964,
    "('KO', 'Close')": 62.885929107666016,
    "('KO', 'Volume')": 12067900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-04 00:00:00",
    "('AAPL', 'Open')": 227.00041910872287,
    "('AAPL', 'High')": 232.87396618357337,
    "('AAPL', 'Low')": 226.40107197135944,
    "('AAPL', 'Close')": 232.54432678222656,
    "('AAPL', 'Volume')": 45067300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.144027276135986,
    "('KO', 'High')": 63.16388122108877,
    "('KO', 'Low')": 61.893255251380204,
    "('KO', 'Close')": 62.21091079711914,
    "('KO', 'Volume')": 15678000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-05 00:00:00",
    "('AAPL', 'Open')": 228.27901582634638,
    "('AAPL', 'High')": 232.4144684638066,
    "('AAPL', 'Low')": 228.0193068583431,
    "('AAPL', 'Close')": 232.21469116210938,
    "('AAPL', 'Volume')": 39620300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.26054811921201,
    "('KO', 'High')": 62.82637230187841,
    "('KO', 'Low')": 62.131499369221466,
    "('KO', 'Close')": 62.657615661621094,
    "('KO', 'Volume')": 10686800,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-06 00:00:00",
    "('AAPL', 'Open')": 231.0359788855247,
    "('AAPL', 'High')": 233.54323203112875,
    "('AAPL', 'Low')": 230.17692277145878,
    "('AAPL', 'Close')": 232.9638671875,
    "('AAPL', 'Volume')": 29925300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.15395247602265,
    "('KO', 'High')": 63.27307614596719,
    "('KO', 'Low')": 62.449154469238444,
    "('KO', 'Close')": 62.89585876464844,
    "('KO', 'Volume')": 13423400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-07 00:00:00",
    "('AAPL', 'Open')": 232.3445476829273,
    "('AAPL', 'High')": 233.74300400322835,
    "('AAPL', 'Low')": 227.0104008794231,
    "('AAPL', 'Close')": 227.3800048828125,
    "('AAPL', 'Volume')": 39707200,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 62.965344756538315,
    "('KO', 'High')": 63.45175314805299,
    "('KO', 'Low')": 62.806516985691296,
    "('KO', 'Close')": 63.37234115600586,
    "('KO', 'Volume')": 13184700,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-10 00:00:00",
    "('AAPL', 'Open')": 229.57000732421875,
    "('AAPL', 'High')": 230.58999633789062,
    "('AAPL', 'Low')": 227.1999969482422,
    "('AAPL', 'Close')": 227.64999389648438,
    "('AAPL', 'Volume')": 33115600,
    "('AAPL', 'Dividends')": 0.25,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 63.6304327473421,
    "('KO', 'High')": 64.17640674155113,
    "('KO', 'Low')": 63.19365733872751,
    "('KO', 'Close')": 64.07714080810547,
    "('KO', 'Volume')": 16154300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-11 00:00:00",
    "('AAPL', 'Open')": 228.1999969482422,
    "('AAPL', 'High')": 235.22999572753906,
    "('AAPL', 'Low')": 228.1300048828125,
    "('AAPL', 'Close')": 232.6199951171875,
    "('AAPL', 'Volume')": 53718400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 67.00553142402087,
    "('KO', 'High')": 67.17428427811407,
    "('KO', 'Low')": 65.92351981112313,
    "('KO', 'Close')": 67.10479736328125,
    "('KO', 'Volume')": 30589100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-12 00:00:00",
    "('AAPL', 'Open')": 231.1999969482422,
    "('AAPL', 'High')": 236.9600067138672,
    "('AAPL', 'Low')": 230.67999267578125,
    "('AAPL', 'Close')": 236.8699951171875,
    "('AAPL', 'Volume')": 45243300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 66.38014756614976,
    "('KO', 'High')": 68.31585984162854,
    "('KO', 'Low')": 66.38014756614976,
    "('KO', 'Close')": 68.2066650390625,
    "('KO', 'Volume')": 26033800,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-13 00:00:00",
    "('AAPL', 'Open')": 236.91000366210938,
    "('AAPL', 'High')": 242.33999633789062,
    "('AAPL', 'Low')": 235.57000732421875,
    "('AAPL', 'Close')": 241.52999877929688,
    "('AAPL', 'Volume')": 53614100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.49454558667519,
    "('KO', 'High')": 69.10007768252483,
    "('KO', 'Low')": 68.25630580956408,
    "('KO', 'Close')": 68.99088287353516,
    "('KO', 'Volume')": 24393100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-14 00:00:00",
    "('AAPL', 'Open')": 241.25,
    "('AAPL', 'High')": 245.5500030517578,
    "('AAPL', 'Low')": 240.99000549316406,
    "('AAPL', 'Close')": 244.60000610351562,
    "('AAPL', 'Volume')": 40896200,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.85190214626031,
    "('KO', 'High')": 69.51699222642839,
    "('KO', 'Low')": 68.25629897635599,
    "('KO', 'Close')": 68.36549377441406,
    "('KO', 'Volume')": 20779100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-18 00:00:00",
    "('AAPL', 'Open')": 244.14999389648438,
    "('AAPL', 'High')": 245.17999267578125,
    "('AAPL', 'Low')": 241.83999633789062,
    "('AAPL', 'Close')": 244.47000122070312,
    "('AAPL', 'Volume')": 48822500,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.04784454064337,
    "('KO', 'High')": 68.86183738196597,
    "('KO', 'Low')": 67.91879199999694,
    "('KO', 'Close')": 68.54418182373047,
    "('KO', 'Volume')": 15569100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-19 00:00:00",
    "('AAPL', 'Open')": 244.66000366210938,
    "('AAPL', 'High')": 246.00999450683594,
    "('AAPL', 'Low')": 243.16000366210938,
    "('AAPL', 'Close')": 244.8699951171875,
    "('AAPL', 'Volume')": 32204200,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.70300098736755,
    "('KO', 'High')": 69.61625970641883,
    "('KO', 'Low')": 68.6632930986907,
    "('KO', 'Close')": 69.55670166015625,
    "('KO', 'Volume')": 16032300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-20 00:00:00",
    "('AAPL', 'Open')": 244.94000244140625,
    "('AAPL', 'High')": 246.77999877929688,
    "('AAPL', 'Low')": 244.2899932861328,
    "('AAPL', 'Close')": 245.8300018310547,
    "('AAPL', 'Volume')": 32316900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.19933972479598,
    "('KO', 'High')": 69.55670315707295,
    "('KO', 'Low')": 68.91146320582254,
    "('KO', 'Close')": 69.52692413330078,
    "('KO', 'Volume')": 13398000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-21 00:00:00",
    "('AAPL', 'Open')": 245.9499969482422,
    "('AAPL', 'High')": 248.69000244140625,
    "('AAPL', 'Low')": 245.22000122070312,
    "('AAPL', 'Close')": 245.5500030517578,
    "('AAPL', 'Volume')": 53197400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.80487039245318,
    "('KO', 'High')": 71.07549253806012,
    "('KO', 'Low')": 69.61625981432218,
    "('KO', 'Close')": 70.82732391357422,
    "('KO', 'Volume')": 21662300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-24 00:00:00",
    "('AAPL', 'Open')": 244.92999267578125,
    "('AAPL', 'High')": 248.86000061035156,
    "('AAPL', 'Low')": 244.4199981689453,
    "('AAPL', 'Close')": 247.10000610351562,
    "('AAPL', 'Volume')": 51326400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.32105986713593,
    "('KO', 'High')": 71.20454716391345,
    "('KO', 'Low')": 69.81480131121985,
    "('KO', 'Close')": 70.07289123535156,
    "('KO', 'Volume')": 21418400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-25 00:00:00",
    "('AAPL', 'Open')": 248,
    "('AAPL', 'High')": 250,
    "('AAPL', 'Low')": 244.91000366210938,
    "('AAPL', 'Close')": 247.0399932861328,
    "('AAPL', 'Volume')": 48013300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.34091872867583,
    "('KO', 'High')": 71.24424862465753,
    "('KO', 'Low')": 70.21187376453723,
    "('KO', 'Close')": 70.96630096435547,
    "('KO', 'Volume')": 21555600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-26 00:00:00",
    "('AAPL', 'Open')": 244.3300018310547,
    "('AAPL', 'High')": 244.97999572753906,
    "('AAPL', 'Low')": 239.1300048828125,
    "('AAPL', 'Close')": 240.36000061035156,
    "('AAPL', 'Volume')": 44433600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.74790745934956,
    "('KO', 'High')": 70.75783632481553,
    "('KO', 'Low')": 70.0133304584795,
    "('KO', 'Close')": 70.28135681152344,
    "('KO', 'Volume')": 14531200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-27 00:00:00",
    "('AAPL', 'Open')": 239.41000366210938,
    "('AAPL', 'High')": 242.4600067138672,
    "('AAPL', 'Low')": 237.05999755859375,
    "('AAPL', 'Close')": 237.3000030517578,
    "('AAPL', 'Volume')": 41153600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.20194264552934,
    "('KO', 'High')": 71.01593544179289,
    "('KO', 'Low')": 69.90413726275992,
    "('KO', 'Close')": 70.35084533691406,
    "('KO', 'Volume')": 16789500,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-02-28 00:00:00",
    "('AAPL', 'Open')": 236.9499969482422,
    "('AAPL', 'High')": 242.08999633789062,
    "('AAPL', 'Low')": 230.1999969482422,
    "('AAPL', 'Close')": 241.83999633789062,
    "('AAPL', 'Volume')": 56833400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.92659426594994,
    "('KO', 'High')": 71.0457179395841,
    "('KO', 'Low')": 70.04311451363778,
    "('KO', 'Close')": 70.6883544921875,
    "('KO', 'Volume')": 22167400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-03 00:00:00",
    "('AAPL', 'Open')": 241.7899932861328,
    "('AAPL', 'High')": 244.02999877929688,
    "('AAPL', 'Low')": 236.11000061035156,
    "('AAPL', 'Close')": 238.02999877929688,
    "('AAPL', 'Volume')": 47184000,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.72545731465965,
    "('KO', 'High')": 71.82993005824459,
    "('KO', 'Low')": 69.2191987540306,
    "('KO', 'Close')": 71.79022216796875,
    "('KO', 'Volume')": 21717600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-04 00:00:00",
    "('AAPL', 'Open')": 237.7100067138672,
    "('AAPL', 'High')": 240.07000732421875,
    "('AAPL', 'Low')": 234.67999267578125,
    "('AAPL', 'Close')": 235.92999267578125,
    "('AAPL', 'Volume')": 53798100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 71.54205239868492,
    "('KO', 'High')": 72.1178054382902,
    "('KO', 'Low')": 69.36809277498888,
    "('KO', 'Close')": 69.67582702636719,
    "('KO', 'Volume')": 25411900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-05 00:00:00",
    "('AAPL', 'Open')": 235.4199981689453,
    "('AAPL', 'High')": 236.5500030517578,
    "('AAPL', 'Low')": 229.22999572753906,
    "('AAPL', 'Close')": 235.74000549316406,
    "('AAPL', 'Volume')": 47227600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.38795340771198,
    "('KO', 'High')": 70.22179640461985,
    "('KO', 'Low')": 69.32838778400009,
    "('KO', 'Close')": 69.56663513183594,
    "('KO', 'Volume')": 23933600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-06 00:00:00",
    "('AAPL', 'Open')": 234.44000244140625,
    "('AAPL', 'High')": 237.86000061035156,
    "('AAPL', 'Low')": 233.16000366210938,
    "('AAPL', 'Close')": 235.3300018310547,
    "('AAPL', 'Volume')": 45170400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.8942184730152,
    "('KO', 'High')": 70.01333457158333,
    "('KO', 'Low')": 68.94124424343562,
    "('KO', 'Close')": 69.94384765625,
    "('KO', 'Volume')": 21694000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-07 00:00:00",
    "('AAPL', 'Open')": 235.11000061035156,
    "('AAPL', 'High')": 241.3699951171875,
    "('AAPL', 'Low')": 234.75999450683594,
    "('AAPL', 'Close')": 239.07000732421875,
    "('AAPL', 'Volume')": 46273600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.13977892180279,
    "('KO', 'High')": 71.29388072187022,
    "('KO', 'Low')": 69.13977892180279,
    "('KO', 'Close')": 70.90673828125,
    "('KO', 'Volume')": 28393300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-10 00:00:00",
    "('AAPL', 'Open')": 235.5399932861328,
    "('AAPL', 'High')": 236.16000366210938,
    "('AAPL', 'Low')": 224.22000122070312,
    "('AAPL', 'Close')": 227.47999572753906,
    "('AAPL', 'Volume')": 72071200,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 71.43285608118927,
    "('KO', 'High')": 72.68362807124566,
    "('KO', 'Low')": 70.79754500733644,
    "('KO', 'Close')": 70.92658996582031,
    "('KO', 'Volume')": 25251200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-11 00:00:00",
    "('AAPL', 'Open')": 223.80999755859375,
    "('AAPL', 'High')": 225.83999633789062,
    "('AAPL', 'Low')": 217.4499969482422,
    "('AAPL', 'Close')": 220.83999633789062,
    "('AAPL', 'Volume')": 76137400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 71.3534428891331,
    "('KO', 'High')": 71.51227445010441,
    "('KO', 'Low')": 70.09274956132249,
    "('KO', 'Close')": 70.51959991455078,
    "('KO', 'Volume')": 28076400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-12 00:00:00",
    "('AAPL', 'Open')": 220.13999938964844,
    "('AAPL', 'High')": 221.75,
    "('AAPL', 'Low')": 214.91000366210938,
    "('AAPL', 'Close')": 216.97999572753906,
    "('AAPL', 'Volume')": 62547500,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.85450842592712,
    "('KO', 'High')": 70.21187185761129,
    "('KO', 'Low')": 69.22911863372708,
    "('KO', 'Close')": 69.42765808105469,
    "('KO', 'Volume')": 18923300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-13 00:00:00",
    "('AAPL', 'Open')": 215.9499969482422,
    "('AAPL', 'High')": 216.83999633789062,
    "('AAPL', 'Low')": 208.4199981689453,
    "('AAPL', 'Close')": 209.67999267578125,
    "('AAPL', 'Volume')": 61368300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.73538281159506,
    "('KO', 'High')": 69.73538281159506,
    "('KO', 'Low')": 68.77248734606556,
    "('KO', 'Close')": 69.11000061035156,
    "('KO', 'Volume')": 15746600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-14 00:00:00",
    "('AAPL', 'Open')": 211.25,
    "('AAPL', 'High')": 213.9499969482422,
    "('AAPL', 'Low')": 209.5800018310547,
    "('AAPL', 'Close')": 213.49000549316406,
    "('AAPL', 'Volume')": 60107600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.51000213623047,
    "('KO', 'High')": 69.26000213623047,
    "('KO', 'Low')": 68.37999725341797,
    "('KO', 'Close')": 69.16000366210938,
    "('KO', 'Volume')": 14205100,
    "('KO', 'Dividends')": 0.51,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-17 00:00:00",
    "('AAPL', 'Open')": 213.30999755859375,
    "('AAPL', 'High')": 215.22000122070312,
    "('AAPL', 'Low')": 209.97000122070312,
    "('AAPL', 'Close')": 214,
    "('AAPL', 'Volume')": 48073400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.23999786376953,
    "('KO', 'High')": 70.16999816894531,
    "('KO', 'Low')": 69.08000183105469,
    "('KO', 'Close')": 70.12000274658203,
    "('KO', 'Volume')": 15634800,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-18 00:00:00",
    "('AAPL', 'Open')": 214.16000366210938,
    "('AAPL', 'High')": 215.14999389648438,
    "('AAPL', 'Low')": 211.49000549316406,
    "('AAPL', 'Close')": 212.69000244140625,
    "('AAPL', 'Volume')": 42432400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.11000061035156,
    "('KO', 'High')": 70.19000244140625,
    "('KO', 'Low')": 69.30000305175781,
    "('KO', 'Close')": 69.37999725341797,
    "('KO', 'Volume')": 12657600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-19 00:00:00",
    "('AAPL', 'Open')": 214.22000122070312,
    "('AAPL', 'High')": 218.75999450683594,
    "('AAPL', 'Low')": 213.75,
    "('AAPL', 'Close')": 215.24000549316406,
    "('AAPL', 'Volume')": 54385400,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.55000305175781,
    "('KO', 'High')": 69.37999725341797,
    "('KO', 'Low')": 68.54000091552734,
    "('KO', 'Close')": 69.27999877929688,
    "('KO', 'Volume')": 14780000,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-20 00:00:00",
    "('AAPL', 'Open')": 213.99000549316406,
    "('AAPL', 'High')": 217.49000549316406,
    "('AAPL', 'Low')": 212.22000122070312,
    "('AAPL', 'Close')": 214.10000610351562,
    "('AAPL', 'Volume')": 48862900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.30999755859375,
    "('KO', 'High')": 69.80999755859375,
    "('KO', 'Low')": 69.08999633789062,
    "('KO', 'Close')": 69.70999908447266,
    "('KO', 'Volume')": 16295300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-21 00:00:00",
    "('AAPL', 'Open')": 211.55999755859375,
    "('AAPL', 'High')": 218.83999633789062,
    "('AAPL', 'Low')": 211.27999877929688,
    "('AAPL', 'Close')": 218.27000427246094,
    "('AAPL', 'Volume')": 94127800,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 69.70999908447266,
    "('KO', 'High')": 69.97000122070312,
    "('KO', 'Low')": 68.18000030517578,
    "('KO', 'Close')": 68.66999816894531,
    "('KO', 'Volume')": 47479500,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-24 00:00:00",
    "('AAPL', 'Open')": 221,
    "('AAPL', 'High')": 221.47999572753906,
    "('AAPL', 'Low')": 218.5800018310547,
    "('AAPL', 'Close')": 220.72999572753906,
    "('AAPL', 'Volume')": 44299500,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.80000305175781,
    "('KO', 'High')": 69.08000183105469,
    "('KO', 'Low')": 68.33000183105469,
    "('KO', 'Close')": 68.94999694824219,
    "('KO', 'Volume')": 12575400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-25 00:00:00",
    "('AAPL', 'Open')": 220.77000427246094,
    "('AAPL', 'High')": 224.10000610351562,
    "('AAPL', 'Low')": 220.0800018310547,
    "('AAPL', 'Close')": 223.75,
    "('AAPL', 'Volume')": 34493600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.94999694824219,
    "('KO', 'High')": 69.08000183105469,
    "('KO', 'Low')": 68.5999984741211,
    "('KO', 'Close')": 68.80999755859375,
    "('KO', 'Volume')": 12513900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-26 00:00:00",
    "('AAPL', 'Open')": 223.50999450683594,
    "('AAPL', 'High')": 225.02000427246094,
    "('AAPL', 'Low')": 220.47000122070312,
    "('AAPL', 'Close')": 221.52999877929688,
    "('AAPL', 'Volume')": 34466100,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 68.91999816894531,
    "('KO', 'High')": 70.3499984741211,
    "('KO', 'Low')": 68.9000015258789,
    "('KO', 'Close')": 70.0199966430664,
    "('KO', 'Volume')": 14478200,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-27 00:00:00",
    "('AAPL', 'Open')": 221.38999938964844,
    "('AAPL', 'High')": 224.99000549316406,
    "('AAPL', 'Low')": 220.55999755859375,
    "('AAPL', 'Close')": 223.85000610351562,
    "('AAPL', 'Volume')": 37094800,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.18000030517578,
    "('KO', 'High')": 70.98999786376953,
    "('KO', 'Low')": 70.06999969482422,
    "('KO', 'Close')": 70.73999786376953,
    "('KO', 'Volume')": 11663400,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-28 00:00:00",
    "('AAPL', 'Open')": 221.6699981689453,
    "('AAPL', 'High')": 223.80999755859375,
    "('AAPL', 'Low')": 217.67999267578125,
    "('AAPL', 'Close')": 217.89999389648438,
    "('AAPL', 'Volume')": 39818600,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.80999755859375,
    "('KO', 'High')": 71.31999969482422,
    "('KO', 'Low')": 69.52999877929688,
    "('KO', 'Close')": 70.37000274658203,
    "('KO', 'Volume')": 17412900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-03-31 00:00:00",
    "('AAPL', 'Open')": 217.00999450683594,
    "('AAPL', 'High')": 225.6199951171875,
    "('AAPL', 'Low')": 216.22999572753906,
    "('AAPL', 'Close')": 222.1300048828125,
    "('AAPL', 'Volume')": 65299300,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 70.7300033569336,
    "('KO', 'High')": 71.94000244140625,
    "('KO', 'Low')": 70.48999786376953,
    "('KO', 'Close')": 71.62000274658203,
    "('KO', 'Volume')": 24016900,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-04-01 00:00:00",
    "('AAPL', 'Open')": 219.80999755859375,
    "('AAPL', 'High')": 223.67999267578125,
    "('AAPL', 'Low')": 218.89999389648438,
    "('AAPL', 'Close')": 223.19000244140625,
    "('AAPL', 'Volume')": 36412700,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 71.68000030517578,
    "('KO', 'High')": 71.91000366210938,
    "('KO', 'Low')": 71.19000244140625,
    "('KO', 'Close')": 71.87000274658203,
    "('KO', 'Volume')": 15309100,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-04-02 00:00:00",
    "('AAPL', 'Open')": 221.32000732421875,
    "('AAPL', 'High')": 225.19000244140625,
    "('AAPL', 'Low')": 221.02000427246094,
    "('AAPL', 'Close')": 223.88999938964844,
    "('AAPL', 'Volume')": 35905900,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 71.95999908447266,
    "('KO', 'High')": 72.36000061035156,
    "('KO', 'Low')": 71.05000305175781,
    "('KO', 'Close')": 71.33000183105469,
    "('KO', 'Volume')": 14606500,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-04-03 00:00:00",
    "('AAPL', 'Open')": 205.5399932861328,
    "('AAPL', 'High')": 207.49000549316406,
    "('AAPL', 'Low')": 201.25,
    "('AAPL', 'Close')": 203.19000244140625,
    "('AAPL', 'Volume')": 103419000,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 72.4800033569336,
    "('KO', 'High')": 73.94999694824219,
    "('KO', 'Low')": 72.31999969482422,
    "('KO', 'Close')": 73.18000030517578,
    "('KO', 'Volume')": 24959600,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  },
  {
    "('Date', '')": "2025-04-04 00:00:00",
    "('AAPL', 'Open')": 193.88999938964844,
    "('AAPL', 'High')": 199.8800048828125,
    "('AAPL', 'Low')": 187.33999633789062,
    "('AAPL', 'Close')": 188.3800048828125,
    "('AAPL', 'Volume')": 125569000,
    "('AAPL', 'Dividends')": 0,
    "('AAPL', 'Stock Splits')": 0,
    "('AAPL', 'Repaired?')": false,
    "('KO', 'Open')": 72.41999816894531,
    "('KO', 'High')": 73.01000213623047,
    "('KO', 'Low')": 69.79000091552734,
    "('KO', 'Close')": 69.93000030517578,
    "('KO', 'Volume')": 26510300,
    "('KO', 'Dividends')": 0,
    "('KO', 'Stock Splits')": 0,
    "('KO', 'Repaired?')": false
  }
]