### Request ###

GET /v1/market/us/status HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 323 
content-type: application/json 
date: Sat,05 Apr 2025 22:58:38 GMT 
server: uvicorn 

{
  "id": "us",
  "name": "U.S. markets",
  "status": "closed",
  "yfit_market_id": "us_market",
  "close": "2025-04-05T20:00:00+00:00",
  "message": "U.S. markets closed",
  "open": "2025-04-05T13:30:00+00:00",
  "yfit_market_status": "YFT_MARKET_CLOSED",
  "timezone": {
    "dst": "true",
    "gmtoffset": "-14400",
    "short": "EDT",
    "$text": "America/New_York"
  },
  "tz": "EDT"
}