### Request ###

GET /v1/market/us/summary HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 4729 
content-type: application/json 
date: Sat,05 Apr 2025 22:59:34 GMT 
server: uvicorn 

{
  "SNP": {
    "language": "en-US",
    "region": "US",
    "quoteType": "INDEX",
    "typeDisp": "Index",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "LOW",
    "shortName": "S&P 500",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": -1325583000000,
    "priceHint": 2,
    "regularMarketChange": -322.43994,
    "regularMarketChangePercent": -5.9749603,
    "regularMarketTime": 1743798958,
    "regularMarketPrice": 5074.08,
    "regularMarketPreviousClose": 5396.52,
    "exchange": "SNP",
    "market": "us_market",
    "fullExchangeName": "SNP",
    "marketState": "CLOSED",
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 0,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "^GSPC"
  },
  "DJI": {
    "language": "en-US",
    "region": "US",
    "quoteType": "INDEX",
    "typeDisp": "Index",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "LOW",
    "shortName": "Dow 30",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": 694362600000,
    "priceHint": 2,
    "regularMarketChange": -2231.0703,
    "regularMarketChangePercent": -5.5025754,
    "regularMarketTime": 1743798958,
    "regularMarketPrice": 38314.86,
    "regularMarketPreviousClose": 40545.93,
    "exchange": "DJI",
    "market": "us_market",
    "fullExchangeName": "DJI",
    "marketState": "CLOSED",
    "sourceInterval": 120,
    "exchangeDataDelayedBy": 0,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "^DJI"
  },
  "NIM": {
    "language": "en-US",
    "region": "US",
    "quoteType": "INDEX",
    "typeDisp": "Index",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "LOW",
    "shortName": "Nasdaq",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": 34612200000,
    "priceHint": 2,
    "regularMarketChange": -962.81934,
    "regularMarketChangePercent": -5.8174267,
    "regularMarketTime": 1743801359,
    "regularMarketPrice": 15587.786,
    "regularMarketPreviousClose": 16550.605,
    "exchange": "NIM",
    "market": "us_market",
    "fullExchangeName": "Nasdaq GIDS",
    "marketState": "CLOSED",
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 0,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "^IXIC"
  },
  "WCB": {
    "language": "en-US",
    "region": "US",
    "quoteType": "INDEX",
    "typeDisp": "Index",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "LOW",
    "shortName": "Russell 2000",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": 558279000000,
    "priceHint": 2,
    "regularMarketChange": -83.51428,
    "regularMarketChangePercent": -4.371225,
    "regularMarketTime": 1743798611,
    "regularMarketPrice": 1827.032,
    "regularMarketPreviousClose": 1910.5463,
    "exchange": "WCB",
    "market": "us_market",
    "fullExchangeName": "Chicago Options",
    "marketState": "CLOSED",
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 15,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "^RUT"
  },
  "NYM": {
    "language": "en-US",
    "region": "US",
    "quoteType": "FUTURE",
    "typeDisp": "Futures",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "NONE",
    "contractSymbol": false,
    "headSymbolAsString": "CL=F",
    "shortName": "Crude Oil",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": 967003200000,
    "regularMarketChange": -4.6299973,
    "regularMarketChangePercent": -6.915605,
    "regularMarketTime": 1743800399,
    "regularMarketPrice": 62.32,
    "regularMarketPreviousClose": 66.95,
    "exchange": "NYM",
    "market": "us24_market",
    "fullExchangeName": "NY Mercantile",
    "marketState": "CLOSED",
    "sourceInterval": 30,
    "exchangeDataDelayedBy": 10,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "CL=F"
  },
  "CMX": {
    "language": "en-US",
    "region": "US",
    "quoteType": "FUTURE",
    "typeDisp": "Futures",
    "quoteSourceName": "Delayed Quote",
    "triggerable": false,
    "customPriceAlertConfidence": "NONE",
    "contractSymbol": false,
    "headSymbolAsString": "GC=F",
    "shortName": "Gold",
    "hasPrePostMarketData": false,
    "firstTradeDateMilliseconds": 967608000000,
    "regularMarketChange": -65.59985,
    "regularMarketChangePercent": -2.1014144,
    "regularMarketTime": 1743800398,
    "regularMarketPrice": 3056.1,
    "regularMarketPreviousClose": 3121.7,
    "exchange": "CMX",
    "market": "us24_market",
    "fullExchangeName": "COMEX",
    "marketState": "CLOSED",
    "sourceInterval": 15,
    "exchangeDataDelayedBy": 10,
    "exchangeTimezoneName": "America/New_York",
    "exchangeTimezoneShortName": "EDT",
    "gmtOffSetMilliseconds": -14400000,
    "esgPopulated": false,
    "tradeable": false,
    "cryptoTradeable": false,
    "symbol": "GC=F"
  }
}