### Request ###

GET /v1/industry/gold/symbol HTTP/1.1
Host: localhost:8000
accept: application/json

### Response ###

## HTTP CODE - 200 ##

HTTP/1.1 200 OK
content-length: 13 
content-type: application/json 
date: Mon,07 Apr 2025 18:39:57 GMT 
server: uvicorn

"^YH10150040"